/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_egamex_jiazai_Utils_Constants */

#ifndef _Included_cn_egamex_jiazai_Utils_Constants
#define _Included_cn_egamex_jiazai_Utils_Constants
#ifdef __cplusplus
extern "C" {
#endif
#undef cn_egamex_jiazai_Utils_Constants_isOutPut
#define cn_egamex_jiazai_Utils_Constants_isOutPut 0L
/*
 * Class:     cn_egamex_jiazai_Utils_Constants
 * Method:    getLocationAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_egamex_jiazai_Utils_Constants_getLocationAddress
  (JNIEnv *, jclass);

/*
 * Class:     cn_egamex_jiazai_Utils_Constants
 * Method:    getPackageName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_egamex_jiazai_Utils_Constants_getPackageName
  (JNIEnv *, jclass);

/*
 * Class:     cn_egamex_jiazai_Utils_Constants
 * Method:    getLoadClassName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_egamex_jiazai_Utils_Constants_getLoadClassName
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
